### ISSUE TITLE
ADO.NETで住所録を作る

### ISSUE THREAD

**Issue by IsseiJinno** [team-itp/workshop#21]
コンソールアプリとして住所録を作成する。
https://github.com/IsseiJinno/MyAdressBook

**Comment by IsseiJinno** [comment]
SQLiteにて住所録テーブルを作成し、各フィールドをキーボード入力により受け付け、INSERT句によって反映した。特に、SQL文に変数を渡す方法としてパラメータを追加するやり方がとても勉強になった。
次回は、一覧表示機能について実装をしていく。

**Comment by chameleonhead** [comment]
活動していないので、消していきます。
