### ISSUE TITLE
レストラン注文システム

### ISSUE THREAD

**Issue by Takenori1110** [team-itp/workshop#35]
レストランで注文を行う上での必要なテーブル定義の検討

**Comment by Takenori1110** [comment]
ハンディを利用して入力情報を親端末へ送信し、親端末で情報管理を行う。
ハンディに登録されているユーザーデータは親端末で設定可能。

**Comment by Takenori1110** [comment]
レストラン注文システムのテーブルと項目を考えてみました。

|テーブル名		|主キー				|項目|
|---|---|---|
|従業員マスタ　　　	|従業員コード			|従業員名|
|席情報マスタ　　　	|席番号　　　			|着席可能人数、着席状態|
|食品メニューマスタ　	|食品コード			|食品名、価格|
|期間食品メニューマスタ　|食品コード			|食品名、価格、販売期間|
|来店客情報トラン　	|来店客ID			|客数、席番号、来店日時|
|オーダー履歴トラン　	|来店客ID、注文ID、食品コード	|注文個数、注文者、注文日時|
|オーダー履歴取消トラン　|来店客ID、注文ID、食品コード	|注文個数、注文者、注文日時|

**Comment by chameleonhead** [comment]
活動していないので、消していきます。
