### ISSUE TITLE
2019年11月3日(日) 勉強会

### ISSUE THREAD

**Issue by chameleonhead** [team-itp/workshop#46]
場所
パインツリー丸の内2F 会議室D

参加者
@chameleonhead 
@match5121 
@yagiiiiiiiiiii 
@SakamotoKazuhiko

**Comment by match5121** [comment]
#4 をやります

**Comment by yagiiiiiiiiiii** [comment]
https://github.com/kkawaguchi/study-group
をやります。

**Comment by chameleonhead** [comment]
#47 をやります。
何かコメントあればお願いします。
