### ISSUE TITLE
2020年6月7日 (日) 勉強会

### ISSUE THREAD

**Issue by chameleonhead** [team-itp/workshop#72]
場所
会議室D

参加者
@chameleonhead 
@match5121 
@kait101

リモート参加
https://join.skype.com/XNjhC4WaCoYR

**Comment by kait101** [comment]
#47　新人メニューをVisual Studio+WPFでやってみる

**Comment by kait101** [comment]
リモート参加
新人メニュー5まで終了

**Comment by chameleonhead** [comment]
お疲れ様でした。
