### ISSUE TITLE
VB.NETとエクセルVBAのツールの使い方を覚える

### ISSUE THREAD

**Issue by yo-naka** [team-itp/workshop#8]
VB6のツールの使い方を理解する。

**Comment by yo-naka** [comment]
3月31日

- [x] プロジェクトを作成
　→コンソールプロジェクト

- [x] 実行する

- [x] デバックする
　→ブレークポイトを置く
　→ステップ実行をする

- [x] もう1個プロジェクトを作る
　→Windows Formsアプリ
　　もう1個のプロジェクトを実行する

**Comment by yo-naka** [comment]
3月31日

  []　Hello　World を表示する

  - []　For文で5回繰り返す

**Comment by yo-naka** [comment]
VB.NETのデバック実行の学習をVisualStudioで実施し、デバックの実行、ブレイクポイントの設定、ステップ実行を理解しました

**Comment by chameleonhead** [comment]
まだ.NETだけなので終わっていません。

**Comment by yo-naka** [comment]
VB6のデバック実行の学習をエクセルのマクロで実施し、VB.NETとの違いを学びました。
　VB6と.NETの違いは、VB6側にはマルチプロジェクトがないので、スタートアッププロジェクトの設定がないと理解しました。

**Comment by chameleonhead** [comment]
お疲れ様です。忘れないようにしてくださいね。
